# Generated by Django 5.1.1 on 2024-10-10 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0003_coursesubscription'),
        ('users', '0003_paymentforcourses'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentforcourses',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materials.course', verbose_name='Курс'),
        ),
    ]
